### ISSUE TITLE
How to evaluate on RLBench tasks.

### ISSUE THREAD

**Issue by choucaicai** [Robot-MA/manipulate-anything#2]
Which file should I run to test the success rate of MA on RLBench tasks in order to reproduce the results in Table 1?

**Comment by jiafei1224** [comment]
Fix the task plan by using the best task plans from the `best_plans_MA` folder, updating the task config files (`.ttm` and `.py`). Note that results may vary slightly due to changes in GPT-4V versions over time.

**Comment by choucaicai** [comment]
Which file should I run to execute the corresponding task?

**Comment by jiafei1224** [comment]
The main script to run is dataset_generator.py, within the script it can set the number of episode to run for the given task.
python dataset_generator.py \
    eval.checkpoint=<PATH_TO_M2T2_CHECKPOINT> \
    eval.mask_thresh=0.0 \
    eval.retract=0.20 \
    rlbench.task_name=<TASK_NAME>

**Comment by choucaicai** [comment]
The Google Drive links in Data Generation Section (step 1, download checkpoint ) appear to be inaccessible.

**Comment by jiafei1224** [comment]
Hi,

sorry about that, i realize i forget to change the access rights of the previous link, i have updated the downloadable version in the new link.
